sudo: required
dist: trusty

language: java

install: ./gradlew assemble
script:
  - "./gradlew check"

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

branches:
  only:
      - master
      - develop
